name: Node CI/CD
on:
  push:
    branches: [ "PictureCI/CD" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: VisualCanada    
  AZURE_WEBAPP_PACKAGE_PATH: client/build    
  NODE_VERSION: '16.x'               
  CONTAINER_REGISTER: ${{ secrets.REGISTRY_URL}}
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present


   
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ visualcanada.scm.azurewebsites.net:443}}

    steps:

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-VisualCanada
      uses: azure/VisualCanada-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

